name: flutter_app_launcher
description: "A Flutter plugin for launching external applications on Android, iOS, and macOS platforms."
version: 0.0.1
homepage: https://github.com/BLAS-Hugo/flutter_app_launcher
repository: https://github.com/BLAS-Hugo/flutter_app_launcher

environment:
  sdk: ^3.9.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.8.0

flutter:
  plugin:
    platforms:
      android:
        package: com.blasdev.flutter_app_launcher
        pluginClass: FlutterAppLauncherPlugin
      ios:
        pluginClass: FlutterAppLauncherPlugin
      macos:
        pluginClass: FlutterAppLauncherPlugin
